# Generated by Django 5.1.2 on 2024-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0002_remove_proveedor_productos_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
