# Generated by Django 5.1 on 2024-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseña_app', '0002_alter_reseña_fecha_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='calificacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='id_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='id_producto',
            field=models.CharField(max_length=100),
        ),
    ]
