# Generated by Django 5.1.2 on 2024-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseña_app', '0003_alter_reseña_calificacion_alter_reseña_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='id_reseña',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
